<?php
namespace CORE\MODELS;
use CORE\MVC\Model;
use CORE\MVC\IModel;
class ForgeryToken extends Model implements IModel
{
    protected static $table="forgery_token";
    protected static $model = [
        'Id'=>['Key'=>true,'Type'=>'Int','Required'=>true, 'ColumnName'=>'id'],
        'Token'=>['Type'=>'Name','Required'=>true,'ColumnName'=>'token'],
        'Date'=>['Type'=>'DateTime','Required'=>false, 'AutoGenerated'=>true,'ColumnName'=>'date']
    ];
    public static function createTable()
    {
        \CORE\DB\DB::query('create table if not exists '.self::$table.' (id int(10) auto_increment key, token text, date timestamp default current_timestamp, index(token(20))) engine InnoDb');
    }
}
