<?php
return[
	'USER'=>[
		'AVATAR'=>'uploads/user/avatar/',
		'RESUME'=>'uploads/user/resume/'
	],
	'COMPANY'=>[
		'LOGO'=>'uploads/company/logo/',
		'DOCS'=>'uploads/company/documents/'
	],
	'SITE'=>[
		'LOGO'=>'assets/assets/img/logo/',
		'FOOTER_LOGO'=>'assets/assets/img/logo/'
	]
];
?>