<?php
namespace MODELS\ADMIN;
use CORE\MVC\Model;
use CORE\MVC\IModel;
class Role extends Model implements IModel
{
    protected static $table="admin_role";
    protected static $model = [
        'Id'=>['Key'=>true,'Type'=>'Int','Required'=>true, 'ColumnName'=>'id'],
        'Title'=>['Type'=>'String', 'Max'=>75,'Min'=>3,'Required'=>true, 'ColumnName'=>'title'],
        'Date'=>['Type'=>'DateTime','Required'=>false,'AutoGenerated'=>true,'ColumnName'=>'date'],
        'Permissions'=>['Type'=>'Array','Required'=>true,'ColumnName'=>'permissions'],
        'Status'=>['Type'=>'Enum','Required'=>true,'ColumnName'=>'status', 'Enum' => '\MODELS\ADMIN\Status', 'Default' => Status::Active]
    ];
    public static function createTable()
    {
        \CORE\DB\DB::query("CREATE TABLE `admin_role` (
          `title` varchar(75) DEFAULT NULL,
          `permissions` text,
          `date` datetime DEFAULT CURRENT_TIMESTAMP,
          `status` tinyint(1) DEFAULT '1',
          `id` tinyint(4) NOT NULL
        ) ENGINE=MyISAM DEFAULT CHARSET=latin1");

        \CORE\DB\DB::query("ALTER TABLE `admin_role`
          ADD PRIMARY KEY (`id`),
          ADD UNIQUE KEY `title` (`title`),
          ADD KEY `id` (`id`),
          ADD KEY `title_2` (`title`(10));
        ");
        \CORE\DB\DB::query("INSERT INTO `admin_role` (`title`, `permissions`, `date`, `status`, `id`) VALUES
        ('Root', 'admin/manageUsers,admin/addUser,admin/editUser,admin/manageRoles,admin/editRole,admin/addRole,default/login,default/home,sample/login,sample/details,sample/loginUser,sample/signup,sample/addUser,sample/index,sample/innerJoin,sample/test,sample/AdminNav,sample/UserNav', '2017-09-24 23:59:38', 1, 1);
        ");
    }
}
